---
- name: update pacakages on server
  shell: |
    sudo apt update && sudo apt upgrade -y
    sudo apt install ca-certificates curl gnupg lsb-release

- name: download key rings and download docker
  shell: |
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt update

- name: install docker
  shell: |
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    docker -v
    systemctl status docker --no-pager -l

- name: assign docker permission to ec2-user
  shell: |
    sudo usermod -aG docker ubuntu


- name: install docker-compose
  shell: |
    sudo apt install docker-compose
